"use client";
import { FormEvent,useCallback,useEffect,useState } from "react";

type Dashboard={generatedAt:number;summary:{rooms:{total:number;active:number;finished:number};players:{total:number;aliases:number};rounds:{total:number;avg_players:number;avg_target:number;exact_hits:number}};recentRooms:Array<{code:string;status:string;round:number;round_seconds:number;winner_name:string|null;created_at:number;player_count:number;rounds_played:number}>;recentRounds:Array<{id:string;room_code:string;round:number;player_count:number;average:number;target:number;winner_name:string;exact_hit:number;created_at:number}>;topPlayers:Array<{player_name:string;avatar:string;rounds:number;wins:number;avg_distance:number}>};

export default function AdminPage(){
  const [key,setKey]=useState("");const [data,setData]=useState<Dashboard|null>(null);const [error,setError]=useState("");const [loading,setLoading]=useState(false);
  const load=useCallback(async(value:string)=>{if(!value)return;setLoading(true);setError("");try{const response=await fetch("/api/admin",{headers:{"x-admin-key":value},cache:"no-store"});const result=await response.json() as Dashboard&{error?:string};if(!response.ok)throw new Error(result.error??"Access denied.");setData(result);sessionStorage.setItem("median-admin-key",value);}catch(e){setData(null);setError(e instanceof Error?e.message:"Could not load analytics.");}finally{setLoading(false);}},[]);
  useEffect(()=>{const saved=sessionStorage.getItem("median-admin-key")??"";if(!saved)return;const timer=window.setTimeout(()=>{setKey(saved);void load(saved);},0);return()=>window.clearTimeout(timer);},[load]);
  const submit=(event:FormEvent)=>{event.preventDefault();void load(key)};
  if(!data)return <main className="admin-login"><div className="admin-card"><img src="/king-diamond.svg" alt=""/><span>K♦ CONTROL ROOM</span><h1>ADMIN<br/>ACCESS</h1><p>Enter the private operator key to view game analytics.</p><form onSubmit={submit}><input type="password" value={key} onChange={e=>setKey(e.target.value)} placeholder="ACCESS KEY" autoFocus required/><button disabled={loading}>{loading?"AUTHENTICATING…":"ENTER CONTROL ROOM →"}</button></form>{error&&<b>{error}</b>}<a href="/">← RETURN TO GAME</a></div></main>;
  const s=data.summary;return <main className="admin-shell"><header><a href="/"><img src="/king-diamond.svg" alt=""/> MEDIAN</a><div><span>ADMIN ANALYTICS</span><small>UPDATED {new Date(data.generatedAt).toLocaleTimeString()}</small></div><button onClick={()=>load(key)}>↻ REFRESH</button></header><section className="admin-title"><div><span>CONTROL ROOM / LIVE DATA</span><h1>GAME<br/><em>INTELLIGENCE</em></h1></div><p>Historical performance and live room activity across the Beauty Contest.</p></section><section className="metric-grid"><Metric label="TOTAL GAMES" value={s.rooms.total}/><Metric label="ACTIVE NOW" value={s.rooms.active} hot/><Metric label="PLAYERS" value={s.players.total}/><Metric label="ROUNDS PLAYED" value={s.rounds.total}/><Metric label="AVG PLAYERS" value={Number(s.rounds.avg_players).toFixed(1)}/><Metric label="AVG TARGET" value={Number(s.rounds.avg_target).toFixed(1)}/><Metric label="EXACT HITS" value={s.rounds.exact_hits??0}/><Metric label="COMPLETED" value={s.rooms.finished??0}/></section><section className="admin-columns"><div className="admin-panel"><div className="panel-title"><span>RECENT GAMES</span><b>{data.recentRooms.length} SHOWN</b></div><div className="admin-table rooms"><div className="tr head"><span>ROOM</span><span>STATUS</span><span>PLAYERS</span><span>ROUNDS</span><span>CREATED</span></div>{data.recentRooms.map(room=><div className="tr" key={room.code}><strong>{room.code}</strong><i className={room.status}>{room.status}</i><span>{room.player_count}</span><span>{room.rounds_played||room.round}</span><time>{new Date(room.created_at).toLocaleDateString()}</time></div>)}</div></div><div className="admin-panel"><div className="panel-title"><span>TOP PLAYERS</span><b>BY ROUND WINS</b></div><div className="leader-list">{data.topPlayers.map((player,index)=><div key={`${player.player_name}-${index}`}><span className={`admin-avatar avatar-${player.avatar}`}>{avatarSymbol(player.avatar)}</span><strong>{player.player_name}<small>{player.rounds} ROUNDS · {player.avg_distance} AVG DIST.</small></strong><b>{player.wins}<small> WINS</small></b></div>)}</div></div></section><section className="admin-panel round-panel"><div className="panel-title"><span>RECENT ROUND TARGETS</span><b>AVERAGE → ×0.8</b></div><div className="round-chart">{data.recentRounds.map(round=><div key={round.id}><span>{round.room_code} · R{round.round}</span><i><b style={{width:`${Math.max(3,round.target)}%`}}/></i><strong>{Number(round.target).toFixed(2)}</strong><small>{round.winner_name}</small></div>)}</div></section></main>;
}
function Metric({label,value,hot=false}:{label:string;value:string|number;hot?:boolean}){return <article className={hot?"hot":""}><span>{label}</span><strong>{value}</strong><i>♦</i></article>}
function avatarSymbol(id:string){return ({diamond:"♦",crown:"♛",laser:"⌁",visa:"03",rabbit:"兔",spade:"♠",heart:"♥",club:"♣"} as Record<string,string>)[id]??"♦"}
