import type { Metadata } from "next";
import { LegalShell } from "../legal-shell";

export const metadata:Metadata={title:"Privacy Policy — Median",description:"How Median collects, uses, shares, and deletes multiplayer game data.",openGraph:{title:"Privacy Policy — Median",description:"How Median handles multiplayer game data.",images:[]},twitter:{title:"Privacy Policy — Median",description:"How Median handles multiplayer game data.",images:[]}};

export default function PrivacyPage(){return <LegalShell kicker="PUBLIC NOTICE / DATA PROTOCOL" title="PRIVACY POLICY" intro="A plain-language account of the information used to run Median. This game has no accounts, advertising trackers, payments, or marketing profiles.">
  <section><h2>1. What this policy covers</h2><p>This policy covers the Median website, its multiplayer rooms, spectator mode, and operator analytics. Median is an independent, non-commercial fan project and is not affiliated with Netflix or the creators, publishers, or rights holders of Alice in Borderland.</p></section>
  <section><h2>2. Information the game collects</h2><ul><li>Your chosen alias and profile symbol.</li><li>Your room membership, host or spectator role, number choices, scores, round results, and elimination status.</li><li>Connection timestamps used to show whether a seat is online and to restore a temporarily interrupted session.</li><li>A random room credential and player session token. The token is stored on your device and is used to reconnect you to the same seat.</li><li>Operator analytics derived from game records, such as room counts, average targets, wins, and recent rounds.</li></ul><p>Do not use your real name or submit sensitive personal information as an alias.</p></section>
  <section><h2>3. Device storage</h2><p>The site uses browser storage for your active room session, sound preference, and—only for the private operator screen—the current admin credential. These are functional storage items, not advertising cookies. The game does not place third-party analytics or advertising cookies.</p></section>
  <section><h2>4. Why the information is used</h2><p>Information is used only to create and run rooms, calculate results, reconnect seats, display live status, support spectators, prevent conflicting room names, diagnose the game, and provide aggregate operator analytics.</p></section>
  <section><h2>5. Who can see it</h2><p>Players and spectators in your room can see your alias, profile symbol, connection status, score, and revealed choices. Choices stay hidden while a round is active. The hosting and database providers process the information needed to deliver the service. Median does not sell personal information or share it for advertising.</p></section>
  <section><h2>6. Retention and deletion</h2><p>When every human player disconnects, an active room is held for two minutes so the players can reconnect. If no human returns, the room and its related player, result, and profile records are deleted. Other retained server-side game records are automatically deleted after 30 days. Your active session is removed from browser storage when you leave, when the room no longer exists, or after a completed match is dismissed. You can also clear site data in your browser at any time.</p></section>
  <section><h2>7. Children</h2><p>Median is a general-audience strategy game and is not directed to children under 13. If you are under 13, do not use the service or submit an alias.</p></section>
  <section><h2>8. Security and your choices</h2><p>Room and player credentials are randomly generated, admin analytics require a private key, and traffic is encrypted in transit. No online service can promise absolute security. Use an alias, keep private room links within your group, and do not share your player session token.</p></section>
  <section><h2>9. Changes and requests</h2><p>This notice may change as the project evolves. Material changes will be dated on this page. Because Median has no user accounts, a room code and valid player session are the only reliable ways to distinguish one player record from another before automatic deletion.</p></section>
</LegalShell>}
