import type { Metadata } from "next";
import { LegalShell } from "../legal-shell";

export const metadata:Metadata={title:"Terms of Use — Median",description:"Terms for using the Median multiplayer strategy game.",openGraph:{title:"Terms of Use — Median",description:"Terms for using the Median multiplayer strategy game.",images:[]},twitter:{title:"Terms of Use — Median",description:"Terms for using the Median multiplayer strategy game.",images:[]}};

export default function TermsPage(){return <LegalShell kicker="PUBLIC NOTICE / CONDITIONS OF ENTRY" title="TERMS OF USE" intro="The rules for using this public preview. By creating, joining, or spectating a room, you agree to these terms.">
  <section><h2>1. Eligibility</h2><p>You must be at least 13 years old to use Median. If local law requires a higher age for online services, that higher age applies.</p></section>
  <section><h2>2. Public-preview service</h2><p>Median is an experimental multiplayer game provided for entertainment. Features, rules, availability, and stored records may change. Rooms may be interrupted or removed, and no uptime or permanent score history is promised.</p></section>
  <section><h2>3. Acceptable use</h2><ul><li>Use an alias and do not impersonate another person.</li><li>Do not submit abusive, unlawful, hateful, sexual, threatening, or privacy-invasive names or content.</li><li>Do not disrupt rooms, automate abusive traffic, bypass access controls, probe private operator tools, or interfere with other players.</li><li>Do not use the service for gambling, prizes, financial stakes, or decisions affecting real-world rights.</li></ul></section>
  <section><h2>4. Rooms and hosts</h2><p>Room hosts control when a match begins, advances, restarts, and—during testing—may adjust scores. Spectators are read-only. Keep room links private if you do not want unknown participants joining.</p></section>
  <section><h2>5. Intellectual property and fan-project notice</h2><p>Median is an unofficial fan-made interpretation of a mathematical beauty-contest game. It is not sponsored, endorsed, or operated by Netflix or by the creators, publishers, producers, or rights holders of Alice in Borderland. Names and marks belonging to third parties remain the property of their respective owners. The site’s original code and interface elements remain with their respective authors.</p></section>
  <section><h2>6. Disclaimer</h2><p>The service is provided “as is” and “as available,” without promises that it will be uninterrupted, error-free, secure, or suitable for a particular purpose. Results are game outcomes only and should not be relied on outside the game.</p></section>
  <section><h2>7. Responsibility</h2><p>To the extent permitted by applicable law, the project operator is not responsible for indirect or consequential loss arising from use of the public preview. Nothing in these terms excludes rights or liability that cannot lawfully be excluded.</p></section>
  <section><h2>8. Suspension and changes</h2><p>Access may be restricted for abuse, security risks, or operational reasons. These terms may be updated as the project develops; the latest effective date appears above.</p></section>
  <section><h2>9. Privacy</h2><p>The <a href="/privacy">Privacy Policy</a> explains the game data used to operate rooms and the 30-day deletion period.</p></section>
</LegalShell>}
